import Header from '../components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import { NextAuthProvider } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Buzz',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
        <Header />
        <div className="bg-[#0F0F0F] h-screen pb-10">
          {children}
        </div>
        </NextAuthProvider>
      </body>
    </html>
  )
}
